# Generated by Django 5.1.6 on 2025-02-28 11:43

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance')], max_length=10)),
                ('resume', models.FileField(upload_to=candidate.models.resume_upload_path)),
            ],
        ),
    ]
