# Generated by Django 5.1.6 on 2025-02-28 16:04

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_auth_id_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='resumes/'),
        ),
    ]
