# Generated by Django 5.1.6 on 2025-02-28 17:01

import candidate.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=candidate.models.resume_upload_path),
        ),
    ]
