# Generated by Django 5.1.6 on 2025-02-28 21:38

import candidate.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_created_candidate_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=candidate.models.resume_upload_path),
        ),
    ]
